<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1511669682594" stop="1511669784850" version="1.5.4" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default Suite : SeleniumJavaAutomation</name>
    <title>Default Suite : SeleniumJavaAutomation</title>
    <test-cases>
        <test-case start="1511669692224" stop="1511669697309" status="failed">
            <name>signInScreen[test_user1,passwrd1]</name>
            <title>Title-TST-1</title>
            <description>Test for Valid_Credentials</description>
            <failure>
                <message>AssertionError: Unable to Login expected [true] but found [false]</message>
                <stack-trace>java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at project.tests.SignInTests.signInScreen(SignInTests.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="SeleniumJavaAutomation"/>
                <label name="testClass" value="project.tests.SignInTests"/>
                <label name="testMethod" value="signInScreen"/>
                <label name="host" value="amarpreet911-Inspiron-N5010"/>
                <label name="thread" value="27416@amarpreet911-Inspiron-N5010.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1511669697311" stop="1511669736878" status="failed">
            <name>signInScreen[test_user2,passwrd2]</name>
            <title>Title-TST-1</title>
            <description>Test for Valid_Credentials</description>
            <failure>
                <message>AssertionError: Unable to Login expected [true] but found [false]</message>
                <stack-trace>java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at project.tests.SignInTests.signInScreen(SignInTests.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="SeleniumJavaAutomation"/>
                <label name="testClass" value="project.tests.SignInTests"/>
                <label name="testMethod" value="signInScreen"/>
                <label name="host" value="amarpreet911-Inspiron-N5010"/>
                <label name="thread" value="27416@amarpreet911-Inspiron-N5010.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1511669736880" stop="1511669776754" status="failed">
            <name>signInScreen[amarpreet911@gmail.com,LinkedinDon@911]</name>
            <title>Title-TST-1</title>
            <description>Test for Valid_Credentials</description>
            <failure>
                <message>AssertionError: Unable to Login expected [true] but found [false]</message>
                <stack-trace>java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at project.tests.SignInTests.signInScreen(SignInTests.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="SeleniumJavaAutomation"/>
                <label name="testClass" value="project.tests.SignInTests"/>
                <label name="testMethod" value="signInScreen"/>
                <label name="host" value="amarpreet911-Inspiron-N5010"/>
                <label name="thread" value="27416@amarpreet911-Inspiron-N5010.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1511669776756" stop="1511669784848" status="broken">
            <name>signInScreen[test_user4,passwrd4]</name>
            <title>Title-TST-1</title>
            <description>Test for Valid_Credentials</description>
            <failure>
                <message>Test was interrupted</message>
            </failure>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="SeleniumJavaAutomation"/>
                <label name="testClass" value="project.tests.SignInTests"/>
                <label name="testMethod" value="signInScreen"/>
                <label name="host" value="amarpreet911-Inspiron-N5010"/>
                <label name="thread" value="27416@amarpreet911-Inspiron-N5010.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1511669682594" stop="1511669784848" status="broken">
            <name>Default Suite : SeleniumJavaAutomation</name>
            <title>Default Suite : SeleniumJavaAutomation</title>
            <failure>
                <message>Test suite was interrupted, some test cases may be lost</message>
            </failure>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
